export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_ANSWERS = "GET_ANSWERS";
export const GET_CORRECT_ANSWER = "GET_CORRECT_ANSWER";
